# Generated by Django 4.0.2 on 2022-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='details',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
