# Generated by Django 4.0.2 on 2022-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deaths',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
