# Generated by Django 4.0.2 on 2022-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_chicken_end_date_chicken_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
