# Generated by Django 4.0.2 on 2022-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_userprofile_editor_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deaths',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
