# Generated by Django 4.0.2 on 2022-06-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_chicken_end_date_alter_chicken_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken',
            name='date',
        ),
    ]
