# Generated by Django 4.0.2 on 2022-06-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_chicken_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chicken',
            old_name='Projected_SP',
            new_name='projected_SP',
        ),
        migrations.RenameField(
            model_name='chicken',
            old_name='Purchased',
            new_name='purchased',
        ),
    ]
