# Generated by Django 4.0.2 on 2022-06-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_expensegroup_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.expensedetails'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.expensegroup'),
        ),
    ]
