# Generated by Django 4.0.2 on 2022-06-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_batch_picture_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='number',
            new_name='number_sold',
        ),
    ]
