# Generated by Django 4.0.2 on 2022-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_expensegroup_details_alter_expenses_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
