# Generated by Django 4.0.2 on 2022-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_expensegroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
