# Generated by Django 4.0.2 on 2022-06-24 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_rename_number_sold_revenue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='/static/images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
