# Generated by Django 4.0.2 on 2022-06-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_deaths_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chicken',
            new_name='Batch',
        ),
        migrations.AddField(
            model_name='deaths',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
    ]
