# Generated by Django 4.0.2 on 2022-06-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_expenses_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
    ]
