# Generated by Django 4.0.2 on 2022-06-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_rename_chicken_batch_deaths_batch_expenses_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deaths',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
    ]
