# Generated by Django 4.0.2 on 2022-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_deaths_batch_alter_expenses_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
