# Generated by Django 4.0.2 on 2022-06-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_expensegroup_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='customer',
        ),
        migrations.AddField(
            model_name='revenue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customers'),
        ),
    ]
