# Generated by Django 4.0.2 on 2022-06-24 07:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_batch_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='batch/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
