# Generated by Django 4.0.2 on 2022-06-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_revenue_customer_revenue_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.batch'),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.expensedetails'),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='group',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='details',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.expensegroup'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customers'),
        ),
    ]
