# Generated by Django 4.0.2 on 2022-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_batch_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
