# Generated by Django 4.0.2 on 2022-06-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_expensegroup_batch_alter_expensegroup_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='details',
        ),
        migrations.DeleteModel(
            name='ExpenseDetails',
        ),
    ]
