# Generated by Django 4.0.2 on 2022-06-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_batch_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
