# Generated by Django 4.0.2 on 2022-06-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_expensegroup_details_delete_expensedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Name',
            new_name='name',
        ),
    ]
