# Generated by Django 4.0.2 on 2022-06-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_editors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='SP',
            new_name='sell_price',
        ),
    ]
