# Generated by Django 4.0.2 on 2022-06-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_rename_sp_revenue_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.batch')),
            ],
        ),
        migrations.DeleteModel(
            name='Editors',
        ),
        migrations.AddField(
            model_name='revenue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customers'),
        ),
    ]
