# Generated by Django 4.0.2 on 2022-06-26 07:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='media/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
