# Generated by Django 4.0.2 on 2022-06-26 07:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_batch_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
