# Generated by Django 4.0.2 on 2022-06-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_batch_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='batch/'),
        ),
    ]
