# Generated by Django 4.0.2 on 2022-06-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_batch_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='picture',
        ),
    ]
