# Generated by Django 4.0.2 on 2022-06-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_revenue_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='animal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense',
            field=models.CharField(choices=[('Food', 'Food'), ('Health', 'Health'), ('Utilities', 'Utilities')], max_length=30),
        ),
    ]
