# Generated by Django 4.0.2 on 2022-06-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_batch_animal_alter_expenses_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='animal',
            field=models.CharField(max_length=30),
        ),
    ]
