# Generated by Django 4.0.2 on 2022-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_batch_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=models.ImageField(default='media/default.jpg', upload_to='batch/'),
        ),
    ]
