# Generated by Django 4.0.2 on 2022-06-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_batch_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='editor',
            new_name='user',
        ),
    ]
