# Generated by Django 4.0.2 on 2022-06-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_rename_editor_batch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
