# Generated by Django 4.0.2 on 2022-06-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_batch_end_date_alter_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
