# Generated by Django 4.0.2 on 2022-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_alter_batch_end_date_alter_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deaths',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(),
        ),
    ]
