# Generated by Django 4.0.2 on 2022-06-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_customers_date_alter_deaths_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.batch'),
        ),
    ]
