# Generated by Django 4.0.2 on 2022-06-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_alter_customers_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='animal',
            new_name='farm',
        ),
    ]
