# Generated by Django 4.0.2 on 2022-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_alter_customers_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='')),
            ],
        ),
    ]
