# Generated by Django 4.0.2 on 2022-06-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_userrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userrs',
            new_name='UserProfile',
        ),
    ]
